language: cpp

compiler:
- gcc

sudo: required

#rvm:
#- gcc_4.9
#- gcc_5.2
#- python_plot
#- gnuplot

# Setup compiler
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- export CXX="g++-4.9"
- export CC="gcc-4.9"
- gcc --version

# Install dependencies: (Boost and python, and setup KAT)
install:

# Boost installation
- wget -q http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download
- mv download boost.tar.gz
- tar -xf boost.tar.gz
- cd boost_1_59_0
- sudo ./bootstrap.sh --with-libraries=chrono,timer,program_options,filesystem,system
- sudo ./b2 -d1 --toolset=gcc-4.9 install
- cd ..

# Samtools installation (just use an old version for now... ideally use V1.3 to be consistent with internal htslib)
- wget -q https://github.com/samtools/samtools/releases/download/1.3/samtools-1.3.tar.bz2
- tar -xf samtools-1.3.tar.bz2
- cd samtools-1.3
- make
- make check
- sudo make install
- cd ..

# Get Dlib
- wget -q http://dlib.net/files/dlib-18.18.tar.bz2
- tar -xf dlib-18.18.tar.bz2
- export CPPFLAGS="$CPPFLAGS -isystem $TRAVIS_BUILD_DIR/dlib-18.18"

# Create portcullis configure script
- ./autogen.sh

# Build portcullis and run tests
script:
- ./configure
- make
- make check
- make distcheck	# Doesn't work due to issue in htslib (don't think htslib is designed to handle this target, I'll need to make some modifcations to support this)

