language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          compiler: gcc
          env: COMPILER=GCC5
        - os: osx
          compiler: clang

# safelist
branches:
  only:
  - master
  - develop

# Setup compiler
before_install:
- ./.travis/before_install.sh

# Install dependencies: (Boost, samtools and dlib)
install:
- ./.travis/install.sh

# Create portcullis configure script
before_script:
- ./autogen.sh

# Build portcullis and run tests
script:
- if [[ "$COMPILER" == "GCC5" ]]; then export CXX="g++-5" && export CC="gcc-5"; else export CXX="g++-4.9" && export CC="gcc-4.9"; fi     
- export PATH="$TRAVIS_BUILD_DIR/exdeps/miniconda/bin:$PATH"
- source activate test-environment
- export LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/exdeps/miniconda/envs/test-environment/lib:$LD_LIBRARY_PATH"
- gcc --version
- g++ --version
- ./configure --disable-silent-rules
- make V=1
- make V=1 check
- make V=1 distcheck

