language: cpp

compiler:
- gcc

sudo: required

#rvm:
#- gcc_4.9
#- gcc_5.2
#- python_plot
#- gnuplot

# Setup compiler
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- sudo apt-get install -qq build-essential
- export CXX="g++-4.9"
- export CC="gcc-4.9"
- gcc --version
- autoconf --version
- automake --version
- m4 --version

# Install dependencies: (Boost, samtools and dlib)
install:

- mkdir -p exdeps
- cd exdeps

# Python3 anaconda
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $TRAVIS_BUILD_DIR/exdeps/miniconda; export PATH="$TRAVIS_BUILD_DIR/exdeps/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=3.5 anaconda
- source activate test-environment;

# Boost installation
- wget -q http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download
- mv download boost.tar.gz
- tar -xf boost.tar.gz
- cd boost_1_59_0
- sudo ./bootstrap.sh --with-libraries=chrono,timer,program_options,filesystem,system
- sudo ./b2 -d0 --toolset=gcc-4.9 install
- cd ..

# Samtools installation (just use an old version for now... ideally use V1.3 to be consistent with internal htslib)
- sudo apt-get install samtools
#- echo "Installing Samtools"
#- wget -q https://github.com/samtools/samtools/releases/download/1.3/samtools-1.3.tar.bz2
#- tar -xf samtools-1.3.tar.bz2
#- cd samtools-1.3
#- make
#- sudo make install
#- cd ..

# Get Dlib
- wget -q http://dlib.net/files/dlib-18.18.tar.bz2
- tar -xf dlib-18.18.tar.bz2
- echo $TRAVIS_BUILD_DIR/exdeps/dlib-18.18
- export CPPFLAGS="$CPPFLAGS -isystem $TRAVIS_BUILD_DIR/exdeps/dlib-18.18"

# Go back
- cd $TRAVIS_BUILD_DIR

# Create portcullis configure script
before_script:
- ./autogen.sh

# Build portcullis and run tests
script:
- ./configure
- make
- make check
- make distcheck

