language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          compiler: gcc
        - os: osx
          compiler: clang

# safelist
branches:
  only:
  - master
  - develop

# Setup compiler
before_install:
- ./.travis/before_install.sh

# Install dependencies: (Boost, samtools and dlib)
install:
- ./.travis/install.sh

# Create portcullis configure script
before_script:
- ./autogen.sh

# Build portcullis and run tests
script:
- export PATH="$HOME/exdeps/miniconda/bin:$PATH"
- source activate test-environment
- export LD_LIBRARY_PATH="$HOME/miniconda/envs/test-environment/lib:$LD_LIBRARY_PATH"
- ./configure --disable-silent-rules
- make
- make check
- make distcheck

