language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          compiler: gcc
        - os: linux
          sudo: required
          compiler: gcc
          env: COMPILER=GCC5
        - os: linux
          sudo: required
          compiler: gcc
          env: COMPILER=GCC6
        - os: linux
          sudo: required
          compiler: gcc
          env: COMPILER=GCC7
        - os: osx
          compiler: clang

# safelist
branches:
  only:
  - master
  - develop


# Install dependencies: samtools
install:
- ./.travis/install.sh

before_script:
# Build boost.  Boost doesn't use autotools so has to be built separately
- ./build_boost.sh
# Create portcullis configure script
- ./autogen.sh

script:
# Sanity check to double check we are using the right compiler on linux
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gcc --version; fi
# Ensure python is configured correctly
- export PATH="$TRAVIS_BUILD_DIR/miniconda/bin:$PATH"
- source activate test-environment
# Configure portcullis for this environment and generate makefiles
- ./configure
# Build portcullis
- make V=1
# Build tests and run
- make V=1 check
# Output result of tests to log for easier debugging.
- cat tests/test-suite.log
